IMDB

In [1]:
import requests
from requests import get
from bs4 import BeautifulSoup
import numpy as np
import re
import pandas as pd
from time import sleep
from random import randint

In [ ]:
# url = "https://www.imdb.com/search/title/?groups=top_1000"
# url = "https://www.imdb.com/search/title/?groups=top_1000&start=51&ref_=adv_nxt"
url = "https://www.imdb.com/search/title/?release_date=1800-01-01,2023-12-31&count=250&start="+page+"&ref_=adv_prv"
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"}
res = requests.get(url,headers=headers)
soup = BeautifulSoup(res.text, "html.parser")

In [32]:
pages = np.arange(1,13230630,250)
print(pages[20])

5001

In [4]:
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"}

for page in pages:
  page = requests.get("https://www.imdb.com/search/title/?release_date=1800-01-01,2023-12-31&count=250&start="+str(page)+"&ref_=adv_prv", headers=headers)

KeyboardInterrupt:

In [ ]:
soup = BeautifulSoup(page.text, 'html.parser')

In [ ]:
print(soup.prettify())

https://developer-ankiwoong.tistory.com/843
https://www.imdb.com/search/title/?groups=top_1000&sort=user_rating,desc

In [ ]:
# 크롤링 속도 제어
sleep(randint(2,10))

In [34]:
# 데이터 변수 리스트 생성
titles = []
years = []
imdb_ratings =[]
metascores = []
votes = []
us_gross = []

In [35]:
pages = np.arange(1,13230630,250)
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36", "Accept-Language": "en-US,en"}

for page in pages:
  page = requests.get("https://www.imdb.com/search/title/?release_date=1800-01-01,2023-12-31&count=250&start="+str(page)+"&ref_=adv_prv", headers=headers)
  soup = BeautifulSoup(page.text, 'html.parser')
  movie_div = soup.find_all('div', class_='lister-item mode-advanced')
  #크롤링 속도 제어
  sleep(randint(2,10))
  for con in movie_div:
    #titles
    name = con.h3.a.text
    titles.append(name)
    # years
    year = con.h3.find('span', class_ = 'lister-item-year').text
    years.append(year)
    #imdb
    imdb = con.find('strong').text if con.find('strong') else 0
    imdb_ratings.append(imdb)
    # meta score
    meta = con.find('span', class_='metascore').text if con.find('span', class_='metascore') else ''
    # if len(con.find('span', class_='metascore').text) > 1:
    #   meta = con.find('span', class_='metascore').text
    metascores.append(meta)
    # else: metascores.append('')
    # votes
    # vote = con.find('span', attrs={'name':"nv"})['data-value'] # attrs: 속성 값 모두 출력
    # if len(vote)>1:
    #   votes.append(int(vote))
    # else:
    #   votes.append('')
    vote = con.find_all('span', attrs={'name':"nv"})[0].text if con.find_all('span', attrs={'name':"nv"}) else 0 
    votes.append(vote)
    # us_gross
    gross = con.find_all('span', attrs={'name':'nv'})[1].text if len(con.find_all('span', attrs={'name':'nv'}))>1 else ''
    us_gross.append(gross)

  print("Done")

Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done

KeyboardInterrupt:

In [36]:
movies = pd.DataFrame({
    'movie' : titles,
    'year' : years,
    'imdb' : imdb_ratings,
    'metascore': metascores,
    'votes' : votes,
    'us_gross_dollars': us_gross 
})

In [37]:
movies.tail()

,movie,year,imdb,metascore,votes,us_gross_dollars
46995,Sex Education,(2019– ),8.3,,"297,848",
46996,John Wick: Chapter 3 - Parabellum,(2019),7.4,73,"384,585",$171.02M
46997,The Vampire Diaries,(2009–2017),7.7,,"330,378",
46998,Accused,(2023– ),7.1,,"3,192",
46999,The Bear,(2022– ),8.4,,"89,857",

#전처리 과정

In [38]:
movies['year']=movies['year'].str.extract('(\d+)').astype(int)

In [80]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47000 entries, 0 to 46999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   movie             47000 non-null  object
 1   year              47000 non-null  int32
 2   imdb              47000 non-null  float64
 3   metascore         16222 non-null  float64
 4   votes             47000 non-null  object
 5   us_gross_dollars  47000 non-null  object
dtypes: float64(2), int32(1), object(3)
memory usage: 2.0+ MB

In [43]:
movies['imdb'] = movies['imdb'].astype(float)

In [41]:
movies['metascore'] = pd.to_numeric(movies['metascore'], errors = 'coerce')
print(movies['metascore'])

0        69.0
1         NaN
2         NaN
3        35.0
4         NaN
         ...
46995     NaN
46996    73.0
46997     NaN
46998     NaN
46999     NaN
Name: metascore, Length: 47000, dtype: float64

In [79]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47000 entries, 0 to 46999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   movie             47000 non-null  object
 1   year              47000 non-null  int32
 2   imdb              47000 non-null  float64
 3   metascore         16222 non-null  float64
 4   votes             47000 non-null  object
 5   us_gross_dollars  47000 non-null  object
dtypes: float64(2), int32(1), object(3)
memory usage: 2.0+ MB

In [75]:
bechdel = pd.read_csv("C:/Users/NTX550/Desktop/권지원/Bechdel-IMDB-project/bechdel4.csv", index_col=0, converters={'imdbid': lambda x: str(x)})

In [83]:
bechdel[bechdel['title'].duplicated(keep=False)]

         id  year                              title    imdbid  rating
43     9583  1893                   Blacksmith Scene   0000005       0
71     9767  1895                   Blacksmith Scene   0000022       0
73     4982  1896            House of the Devil, The   0000091       0
86     5914  1899                         Cinderella   0000230       3
102    5431  1902             Gulliver&#39;s Travels   0229024       0
...     ...   ...                                ...       ...     ...
9848  10595  2022                      Stranger, The  11897478       3
9876  10684  2022                             Willow  10278918       3
9883  10698  2022                        White Noise   6160448       3
9893  10734  2022  What&#39;s Love Got to Do with It  13430858       1
9899  10754  2023                            Missing  10855768       3

[467 rows x 5 columns]

In [87]:
nnew = bechdel.drop_duplicates(['title'],keep='first')

In [94]:
nnew.reset_index(drop=True)

         id  year                              title    imdbid  rating
0      9602  1874                   Passage de Venus   3155794       0
1      9804  1877                  La Rosace Magique  14495706       0
2      9603  1878         Sallie Gardner at a Gallop   2221420       0
3      9806  1878                  Le singe musicien  12592084       0
4      9816  1881            Athlete Swinging a Pick   7816420       0
...     ...   ...                                ...       ...     ...
9650  10756  2023  Ant-Man and the Wasp: Quantumania  10954600       3
9651  10728  2023                            Pathaan  12844910       3
9652  10737  2023                      Infinity Pool  10365998       2
9653  10779  2023                       Cocaine Bear  14209916       3
9654  10785  2023                 Les choses simples  25971180       1

[9655 rows x 5 columns]

In [100]:
movies[movies['title']=='Cocaine Bear']

KeyError: 'title'

In [97]:
new = pd.merge(left = nnew, right = movies, left_on = ['title','year'], right_on= ['movie','year'] )

In [98]:
new

,id,year,title,imdbid,rating,movie,imdb,metascore,votes,us_gross_dollars
0,1267,1927,Metropolis,0017136,1,Metropolis,8.3,98.0,"177,780",$1.24M
1,1316,1930,All Quiet on the Western Front,0020629,0,All Quiet on the Western Front,8.1,91.0,"65,329",$3.27M
2,610,1931,M,0022100,3,M,8.3,NaN,"161,255",$0.03M
3,1317,1931,Frankenstein,0021884,1,Frankenstein,7.8,91.0,"75,420",
4,1985,1931,Dracula,0021814,2,Dracula,7.4,71.0,"54,966",
...,...,...,...,...,...,...,...,...,...,...
6520,10779,2023,Cocaine Bear,14209916,3,Cocaine Bear,6.0,54.0,"63,555",
6521,10779,2023,Cocaine Bear,14209916,3,Cocaine Bear,6.0,54.0,"63,555",
6522,10779,2023,Cocaine Bear,14209916,3,Cocaine Bear,6.0,54.0,"63,555",
6523,10779,2023,Cocaine Bear,14209916,3,Cocaine Bear,6.0,54.0,"63,555",
6524,10779,2023,Cocaine Bear,14209916,3,Cocaine Bear,6.0,54.0,"63,555",

In [81]:
movies

,movie,year,imdb,metascore,votes,us_gross_dollars
0,Evil Dead Rise,2023,7.1,69.0,"30,771",
1,The Diplomat,2023,8.2,NaN,"17,647",
2,Succession,2018,8.8,NaN,"181,293",
3,Ghosted,2023,5.8,35.0,"27,622",
4,Beef,2023,8.2,NaN,"58,585",
...,...,...,...,...,...,...
46995,Sex Education,2019,8.3,NaN,"297,848",
46996,John Wick: Chapter 3 - Parabellum,2019,7.4,73.0,"384,585",$171.02M
46997,The Vampire Diaries,2009,7.7,NaN,"330,378",
46998,Accused,2023,7.1,NaN,"3,192",
46999,The Bear,2022,8.4,NaN,"89,857",

In [78]:
new

,id,year,title,imdbid,rating,movie,imdb,metascore,votes,us_gross_dollars
0,9602,1874,Passage de Venus,3155794,0,NaN,NaN,NaN,NaN,NaN
1,9804,1877,La Rosace Magique,14495706,0,NaN,NaN,NaN,NaN,NaN
2,9603,1878,Sallie Gardner at a Gallop,2221420,0,NaN,NaN,NaN,NaN,NaN
3,9806,1878,Le singe musicien,12592084,0,NaN,NaN,NaN,NaN,NaN
4,9816,1881,Athlete Swinging a Pick,7816420,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
13895,10779,2023,Cocaine Bear,14209916,3,Cocaine Bear,6.0,54.0,"63,555",
13896,10779,2023,Cocaine Bear,14209916,3,Cocaine Bear,6.0,54.0,"63,555",
13897,10779,2023,Cocaine Bear,14209916,3,Cocaine Bear,6.0,54.0,"63,555",
13898,10779,2023,Cocaine Bear,14209916,3,Cocaine Bear,6.0,54.0,"63,555",
13899,10785,2023,Les choses simples,25971180,1,NaN,NaN,NaN,NaN,NaN

In [64]:
new.drop('movie', axis=1, inplace=True)

In [70]:
new.drop_duplicates(subset=None, keep='first', inplace=False, ignore_index=False)

,id,year,title,imdbid,rating,imdb,metascore,votes,us_gross_dollars
0,1267,1927,Metropolis,0017136,1,8.3,98.0,"177,780",$1.24M
1,1316,1930,All Quiet on the Western Front,0020629,0,8.1,91.0,"65,329",$3.27M
2,610,1931,M,0022100,3,8.3,NaN,"161,255",$0.03M
3,1317,1931,Frankenstein,0021884,1,7.8,91.0,"75,420",
4,1985,1931,Dracula,0021814,2,7.4,71.0,"54,966",
...,...,...,...,...,...,...,...,...,...
6494,10756,2023,Ant-Man and the Wasp: Quantumania,10954600,3,6.2,48.0,"123,810",
6643,10728,2023,Pathaan,12844910,3,6.0,47.0,"137,306",
6644,10754,2023,Missing,10855768,3,7.1,66.0,"27,113",
6645,10737,2023,Infinity Pool,10365998,2,6.1,72.0,"28,029",
6794,10779,2023,Cocaine Bear,14209916,3,6.0,54.0,"63,555",

In [ ]:
movies['Dollars(Millions)'] = movies['us_gross_dollars']

In [ ]:
for i in range(len(movies)):
  if movies.loc[i,'us_gross_dollars'].startswith('$'):
    movies.loc[i,'Dollars(Millions)'] = movies.loc[i,'us_gross_dollars']
  else: movies.loc[i,'Dollars(Millions)'] = ''

In [ ]:
movies.drop('us_gross_dollars',axis='columns',inplace = True)

In [ ]:
movies.rename(columns = {'Dollars(Millions)': 'us_gross(millions)'}, inplace = True)

In [ ]:
movies['us_gross(millions)']=movies['us_gross(millions)'].map(lambda x: x.lstrip('$').rstrip('M'))

In [ ]:
movies['us_gross(millions)'] = pd.to_numeric(movies['us_gross(millions)'],errors = 'coerce')

In [ ]:
# 결측치 확인
print(movies.isnull().sum())

movie                   0
year                    0
imdb                    0
metascore             156
votes                   0
us_gross(millions)    185
dtype: int64

In [ ]:
movies.to_csv('IMDB.csv')

In [ ]:
movies

,movie,year,imdb,metascore,votes,us_gross(millions)
0,John Wick: Chapter 4,2023,8.2,78.0,"136,942",NaN
1,Avatar: The Way of Water,2022,7.7,67.0,"369,149",659.68
2,Everything Everywhere All at Once,2022,7.9,81.0,"436,605",72.86
3,Top Gun: Maverick,2022,8.3,78.0,"577,027",718.73
4,The Whale,2022,7.7,60.0,"135,462",NaN
...,...,...,...,...,...,...
995,Nefes: Vatan Sagolsun,2009,8.0,NaN,"34,335",NaN
996,Sarfarosh,1999,8.1,NaN,"26,176",NaN
997,Baby,2015,7.9,NaN,"58,727",NaN
998,Her Sey Çok Güzel Olacak,1998,8.1,NaN,"26,211",NaN
999,Anand,1971,8.1,NaN,"34,367",NaN